uplode code

diff --git a/project b/project
--- a/project
+++ b/project
@@ -1,73 +1,82 @@
 #!/bin/bash
+mkdir DBMS 2>> ./.error.log
+clear
+echo "Welcome To DBMS"
 
-# global variable to store the current database name
-current_db=""
-
-main_menu() {
-  clear
-  echo "Main Menu:"
-  echo "1. Create Database"
-  echo "2. List Databases"
-  echo "3. Connect To Database"
-  echo "4. Drop Database"
-  echo "5. Exit"
-  read -p "Enter your choice: " choice
-  case $choice in
-    1) create_database;;
-    2) list_databases;;
-    3) connect_to_database;;
-    4) drop_database;;
-    5) exit;;
-    *) echo "Invalid choice. Please try again."; main_menu;;
+function mainMenu {
+  echo -e "\n+---------Main Menu-------------+"
+  echo "| 1. Select DB                  |"
+  echo "| 2. Create DB                  |"
+  echo "| 3. Rename DB                  |"
+  echo "| 4. Drop DB                    |"
+  echo "| 5. Show DBs                   |"
+  echo "| 6. Exit                       |"
+  echo "+-------------------------------+"
+  echo -e "Enter Choice: \c"
+  read ch
+  case $ch in
+    1)  selectDB ;;
+    2)  createDB ;;
+    3)  renameDB ;;
+    4)  dropDB ;;
+    5)  ls ./DBMS ; mainMenu;;
+    6) exit ;;
+    *) echo " Wrong Choice " ; mainMenu;
   esac
 }
 
-create_database() {
-  read -p "Enter the name of the new database: " db_name
-  # check if the database already exists
-  if [ -d "$db_name" ]; then
-    echo "Error: Database already exists."
-    main_menu
+function selectDB {
+  echo -e "Enter Database Name: \c"
+  read dbName
+  cd ./DBMS/$dbName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database $dbName was Successfully Selected"
+    tablesMenu
   else
-    mkdir $db_name
-    echo "Database $db_name created successfully."
-    main_menu
+    echo "Database $dbName wasn't found"
+    mainMenu
   fi
 }
 
-list_databases() {
-  echo "List of databases:"
-  ls -l | grep "^d" | awk '{print $9}'
-  main_menu
-}
-
-connect_to_database() {
-  read -p "Enter the name of the database to connect to: " db_name
-  # check if the database exists
-  if [ -d "$db_name" ]; then
-    current_db=$db_name
-    table_menu
+function createDB {
+  echo -e "Enter Database Name: \c"
+  read dbName
+  mkdir ./DBMS/$dbName
+  if [[ $? == 0 ]]
+  then
+    echo "Database Created Successfully"
   else
-    echo "Error: Database not found."
-    main_menu
+    echo "Error Creating Database $dbName"
   fi
+  mainMenu
 }
 
-drop_database() {
-  read -p "Enter the name of the database to drop: " db_name
-  # check if the database exists
-  if [ -d "$db_name" ]; then
-    rm -r $db_name
-    echo "Database $db_name dropped successfully."
-    main_menu
+function renameDB {
+  echo -e "Enter Current Database Name: \c"
+  read dbName
+  echo -e "Enter New Database Name: \c"
+  read newName
+  mv ./DBMS/$dbName ./DBMS/$newName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database Renamed Successfully"
   else
-    echo "Error: Database not found."
-    main_menu
+    echo "Error Renaming Database"
   fi
+  mainMenu
 }
 
+function dropDB {
+  echo -e "Enter Database Name: \c"
+  read dbName
+  rm -r ./DBMS/$dbName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database Dropped Successfully"
+  else
+    echo "Database Not found"
+  fi
+  mainMenu
+}
 
-main_menu
 
 
 # Mahmoud Ali Ahmed 
@@ -127,11 +136,11 @@ function createTable {
     read colName
 
     echo -e "Type of Column $colName: "
-    select var in "1.int" "2.str"
+    select var in "int" "str"
     do
       case $var in
-        1 ) colType="int";break;;
-        2 ) colType="str";break;;
+        int ) colType="int";break;;
+        str ) colType="str";break;;
         * ) echo "Wrong Choice" ;;
       esac
     done
@@ -250,3 +259,204 @@ function insert {
   row=""
   tablesMenu
 }
+
+
+function updateTable {
+  echo -e "Enter Table Name: \c"
+  read tName
+  echo -e "Enter Condition Column name: \c"
+  read field
+  fid=$(awk 'BEGIN{FS="|"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tName)
+  if [[ $fid == "" ]]
+  then
+    echo "Not Found"
+    tablesMenu
+  else
+    echo -e "Enter Condition Value: \c"
+    read val
+    res=$(awk 'BEGIN{FS="|"}{if ($'$fid'=="'$val'") print $'$fid'}' $tName 2>>./.error.log)
+    if [[ $res == "" ]]
+    then
+      echo "Value Not Found"
+      tablesMenu
+    else
+      echo -e "Enter FIELD name to set: \c"
+      read setField
+      setFid=$(awk 'BEGIN{FS="|"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$setField'") print i}}}' $tName)
+      if [[ $setFid == "" ]]
+      then
+        echo "Not Found"
+        tablesMenu
+      else
+        echo -e "Enter new Value to set: \c"
+        read newValue
+        NR=$(awk 'BEGIN{FS="|"}{if ($'$fid' == "'$val'") print NR}' $tName 2>>./.error.log)
+        oldValue=$(awk 'BEGIN{FS="|"}{if(NR=='$NR'){for(i=1;i<=NF;i++){if(i=='$setFid') print $i}}}' $tName 2>>./.error.log)
+        echo $oldValue
+        sed -i ''$NR's/'$oldValue'/'$newValue'/g' $tName 2>>./.error.log
+        echo "Row Updated Successfully"
+        tablesMenu
+      fi
+    fi
+  fi
+}
+
+function deleteFromTable {
+  echo -e "Enter Table Name: \c"
+  read tName
+  echo -e "Enter Condition Column name: \c"
+  read field
+  fid=$(awk 'BEGIN{FS="|"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tName)
+  if [[ $fid == "" ]]
+  then
+    echo "Not Found"
+    tablesMenu
+  else
+    echo -e "Enter Condition Value: \c"
+    read val
+    res=$(awk 'BEGIN{FS="|"}{if ($'$fid'=="'$val'") print $'$fid'}' $tName 2>>./.error.log)
+    if [[ $res == "" ]]
+    then
+      echo "Value Not Found"
+      tablesMenu
+    else
+      NR=$(awk 'BEGIN{FS="|"}{if ($'$fid'=="'$val'") print NR}' $tName 2>>./.error.log)
+      sed -i ''$NR'd' $tName 2>>./.error.log
+      echo "Row Deleted Successfully"
+      tablesMenu
+    fi
+  fi
+}
+
+function selectMenu {
+  echo -e "\n\n+---------------Select Menu--------------------+"
+  echo "| 1. Select All Columns of a Table              |"
+  echo "| 2. Select Specific Column from a Table        |"
+  echo "| 3. Select From Table under condition          |"
+  echo "| 4. Aggregate Function for a Specific Column   |"
+  echo "| 5. Back To Tables Menu                        |"
+  echo "| 6. Back To Main Menu                          |"
+  echo "| 7. Exit                                       |"
+  echo "+----------------------------------------------+"
+  echo -e "Enter Choice: \c"
+  read ch
+  case $ch in
+    1) selectAll ;;
+    2) selectCol ;;
+    3) clear; selectCon ;;
+    4) ;;
+    5) clear; tablesMenu ;;
+    6) clear; cd ../.. 2>>./.error.log; mainMenu ;;
+    7) exit ;;
+    *) echo " Wrong Choice " ; selectMenu;
+  esac
+}
+
+function selectAll {
+  echo -e "Enter Table Name: \c"
+  read tName
+  column -t -s '|' $tName 2>>./.error.log
+  if [[ $? != 0 ]]
+  then
+    echo "Error Displaying Table $tName"
+  fi
+  selectMenu
+}
+
+function selectCol {
+  echo -e "Enter Table Name: \c"
+  read tName
+  echo -e "Enter Column Number: \c"
+  read colNum
+  awk 'BEGIN{FS="|"}{print $'$colNum'}' $tName
+  selectMenu
+}
+
+function selectCon {
+  echo -e "--------Select Under Condition Menu-----------"
+  echo "| 1. Select All Columns Matching Condition "
+  echo "| 2. Select Specific Column Matching Condition"
+  echo "| 3. Back To Selection Menu"
+  echo "| 4. Back To Main Menu "
+  echo "| 5. Exit"
+  echo -e "Enter Choice: \c"
+  read ch
+  case $ch in
+    1) clear; allCond ;;
+    2) clear; specCond ;;
+    3) clear; selectCon ;;
+    4) clear; cd ../.. 2>>./.error.log; mainMenu ;;
+    5) exit ;;
+    *) echo " Wrong Choice " ; selectCon;
+  esac
+}
+
+function allCond {
+  echo -e "Select all columns from TABLE Where FIELD(OPERATOR)VALUE \n"
+  echo -e "Enter Table Name: \c"
+  read tName
+  echo -e "Enter required FIELD name: \c"
+  read field
+  fid=$(awk 'BEGIN{FS="|"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tName)
+  if [[ $fid == "" ]]
+  then
+    echo "Not Found"
+    selectCon
+  else
+    echo -e "\nSupported Operators: [==, !=, >, <, >=, <=] \nSelect OPERATOR: \c"
+    read op
+    if [[ $op == "==" ]] || [[ $op == "!=" ]] || [[ $op == ">" ]] || [[ $op == "<" ]] || [[ $op == ">=" ]] || [[ $op == "<=" ]]
+    then
+      echo -e "\nEnter required VALUE: \c"
+      read val
+      res=$(awk 'BEGIN{FS="|"}{if ($'$fid$op$val') print $0}' $tName 2>>./.error.log |  column -t -s '|')
+      if [[ $res == "" ]]
+      then
+        echo "Value Not Found"
+        selectCon
+      else
+        awk 'BEGIN{FS="|"}{if ($'$fid$op$val') print $0}' $tName 2>>./.error.log |  column -t -s '|'
+        selectCon
+      fi
+    else
+      echo "Unsupported Operator\n"
+      selectCon
+    fi
+  fi
+}
+
+function specCond {
+  echo -e "Select specific column from TABLE Where FIELD(OPERATOR)VALUE \n"
+  echo -e "Enter Table Name: \c"
+  read tName
+  echo -e "Enter required FIELD name: \c"
+  read field
+  fid=$(awk 'BEGIN{FS="|"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tName)
+  if [[ $fid == "" ]]
+  then
+    echo "Not Found"
+    selectCon
+  else
+    echo -e "\nSupported Operators: [==, !=, >, <, >=, <=] \nSelect OPERATOR: \c"
+    read op
+    if [[ $op == "==" ]] || [[ $op == "!=" ]] || [[ $op == ">" ]] || [[ $op == "<" ]] || [[ $op == ">=" ]] || [[ $op == "<=" ]]
+    then
+      echo -e "\nEnter required VALUE: \c"
+      read val
+      res=$(awk 'BEGIN{FS="|"; ORS="\n"}{if ($'$fid$op$val') print $'$fid'}' $tName 2>>./.error.log |  column -t -s '|')
+      if [[ $res == "" ]]
+      then
+        echo "Value Not Found"
+        selectCon
+      else
+        awk 'BEGIN{FS="|"; ORS="\n"}{if ($'$fid$op$val') print $'$fid'}' $tName 2>>./.error.log |  column -t -s '|'
+        selectCon
+      fi
+    else
+      echo "Unsupported Operator\n"
+      selectCon
+    fi
+  fi
+}
+
+mainMenu
